[package]
name = "ollama-client"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    ".",
    "crates/llms",
    "crates/benchmarks",
    "crates/benchmarks/tests/comparison_tests/simple/simple_1/harness_rs",
    "crates/benchmarks/tests/comparison_tests/agents/math_agent/harness_rs",
    "crates/benchmarks/tests/comparison_tests/agents/research_agent/harness_rs",
    "crates/benchmarks/tests/comparison_tests/agents/text_agent/harness_rs",
    "crates/benchmarks/tests/comparison_tests/agents/database_agent/harness_rs",
    "crates/benchmarks/tests/comparison_tests/agents/finance_agent/harness_rs",
    "/home/shikhars/Documents/shikhar/Documents/yotta/ollama-client/Cargo.toml",
]

[dependencies]
dotenvy = "0.15"
llms = { version = "0.1.0", path = "./crates/llms" , features = ["tinylog"]}
reqwest = { version = "0.13.4", features = ["json"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
tokio = { version = "1.52.3", features = ["full"] }
